<?php

namespace SondageBundle\Repository;

/**
 * Rep_questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rep_questionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRepsByQuestionID($q_id)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT  p.id as id,  p.reponse as reponse FROM SondageBundle:Rep_question p WHERE (p.question = '.$q_id.')')
            ->execute();
    }
}
