<?php

namespace SondageBundle\Repository;

/**
 * Rep_question_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rep_question_userRepository extends \Doctrine\ORM\EntityRepository
{
}
