<?php

namespace SondageBundle\Repository;

/**
 * reponseQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
