<?php

namespace SondageBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getReponseByQuestion($pattern)
    {
        return $this
            ->createQueryBuilder('r')
            ->where('r.question = :ID')
            ->setParameter('ID',$pattern);
            
            //->leftJoin('a.id LIKE 12','question')
            //->addSelect('question');
            
            //->where('r.id_question LIKE :pattern')
            //->setParameter('pattern', $pattern);
    }
    
}
