<?php

namespace SondageBundle\Repository;

/**
 * ReponseSondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseSondageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRepBySondageID($id)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT p FROM SondageBundle:ReponseSondage p WHERE p.sondage = '.$id.'')
            ->execute();
    }

    public function findRep($id)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT p.reponse as Reponse, COUNT( p.reponse) as Reps FROM SondageBundle:ReponseSondage p where p.sondage = '.$id.' GROUP BY p.reponse ' )
            ->execute();
    }
    public function setForm( $id, $pk, $age, $msg, $p){


        $qb = $this->getEntityManager()->createQueryBuilder();
        $q = $qb->update('SondageBundle:ReponseSondage', 'u')
            ->set('u.sondage_q', $qb->expr()->literal($pk))
            ->set('u.age', $qb->expr()->literal($age))
            ->set('u.message', $qb->expr()->literal($msg))
            ->set('u.profession', $qb->expr()->literal($p))
            ->where('u.idsession = ?1')
            ->setParameter(1, $id)
            ->getQuery();
        $q->execute();}









}
