<?php

namespace PetitionBundle\Repository;

/**
 * PetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPetitionByUserID($user)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PetitionBundle:Petition p WHERE p.user = '.$user.'')
            ->execute();
    }

    public function findsearch($data)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PetitionBundle:Petition p WHERE p.nom Like :searchterm')
            ->setParameter('searchterm', '%'.$data['Rechercher'].'%')
            ->execute();
    }

    public function findPetitionByThemeID($theme)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PetitionBundle:Petition p WHERE p.theme = '.$theme.'')
            ->execute();
    }
}
