<?php

namespace PetitionBundle\Repository;

/**
 * SignatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignatureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSignatureByPetitionID($id)
    {

        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PetitionBundle:Signature p WHERE p.petition = '.$id.'')
            ->execute();
    }

    public function setForm( $id, $pk, $age, $msg, $p){


        $qb = $this->getEntityManager()->createQueryBuilder();
        $q = $qb->update('PetitionBundle:Signature', 'u')
            ->set('u.petition_q', $qb->expr()->literal($pk))
            ->set('u.age', $qb->expr()->literal($age))
            ->set('u.message', $qb->expr()->literal($msg))
            ->set('u.profession', $qb->expr()->literal($p))
            ->where('u.idsession = ?1')
            ->setParameter(1, $id)
            ->getQuery();
        $q->execute();}


        public function findPetitionBySignatureCount(){

            return $this->getEntityManager()
                ->createQuery('SELECT count(S.petition) as cnt, P as petition FROM PetitionBundle:Signature S JOIN PetitionBundle:Petition P WITH P.id = S.petition GROUP BY S.petition ORDER BY cnt DESC ')
                ->execute();


        }


    }


